version: '3.3'

volumes:
    db-data:
      
services:
  # Postgres
  db:
    image: postgres
    ports:
      - "57002:5432"
    environment:
      - POSTGRES_USER=meuslivroslidos
      - POSTGRES_PASSWORD=meuslivroslidos
      - POSTGRES_DB=meuslivroslidos              
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  
  redis:
    image: redis:3.2

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    links:
      - db
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    container_name: celery
    command: celery --app=meusLivrosLidos worker --loglevel=INFO
    volumes:
      - ..:/src
    links:
      - db
      - redis
  
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

  

# A montagem deste docker-compose foi com base no django-cookiecutter
