# Generated by Django 2.0.3 on 2018-03-23 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Série')),
                ('num_paginas', models.IntegerField(blank=True, null=True, verbose_name='Número de páginas')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Começou em')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Terminou em')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='Nota')),
                ('ebook', models.BooleanField(verbose_name='É um ebook')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livro_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
    ]
