# Generated by Django 2.0.3 on 2018-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Impressões'),
        ),
    ]
